/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-12-21 00:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class look_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>观看内容</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.demo2-bg{\r\n");
      out.write("\t\t    background: url(img/样式0.jpg) no-repeat;\r\n");
      out.write("\t\t    background-size: cover;\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t    height: 100%;\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.demo1-bg{\r\n");
      out.write("\t\t    background: url(img/dan2.jpg) no-repeat;\r\n");
      out.write("\t\t    background-size: cover;\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t    height: 100%;\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.demo2{\r\n");
      out.write("\t\t    position: absolute;\r\n");
      out.write("\t\t    left: 0;\r\n");
      out.write("\t\t    right: 0;\r\n");
      out.write("\t\t    top: 0;\r\n");
      out.write("\t\t    bottom: 0;\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t    height: 100%;\r\n");
      out.write("\t\t    line-height: 30px;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    background:rgba(255,255,255,0.3);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.sumbit{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.button2\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tbackground-color:#FFD700; \r\n");
      out.write("\t\t    border: none;\r\n");
      out.write("\t\t    color: white;\r\n");
      out.write("\t\t    padding:  8px 10px;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    text-decoration: none;\r\n");
      out.write("\t\t    display: inline-block;\r\n");
      out.write("\t\t    font-size: 16px;\r\n");
      out.write("\t\t    line-height:16px;\r\n");
      out.write("\t\t     box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t.button1\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\tbackground-color:#ed1941; \r\n");
      out.write("\t\t    border: none;\r\n");
      out.write("\t\t    color: white;\r\n");
      out.write("\t\t    padding:  8px 10px;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    text-decoration: none;\r\n");
      out.write("\t\t    display: inline-block;\r\n");
      out.write("\t\t    font-size: 16px;\r\n");
      out.write("\t\t    line-height:16px;\r\n");
      out.write("\t\t     box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"demo2-bg\" style=\"margin:auto;width:500px; height:100px;\">\r\n");
      out.write("<div class=\"demo2\">\r\n");
      out.write("<h2>查看梦的内容</h2>    \r\n");
      out.write("    \t<input type=\"hidden\" name=\"dream1.id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dream.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    \t<div>\r\n");
      out.write("   \t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ biaoqian.b_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \t\t\r\n");
      out.write("       \t</div>\r\n");
      out.write("\t\t <div> \r\n");
      out.write("\t\t    睡觉时间：<input type=\"datetime-local\" name=\"start\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t\t    起床时间：<input type=\"datetime-local\" name=\"end\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ end }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("    \t<div>\r\n");
      out.write("    \t标题：<input type=\"text\" name=\"dream1.dreamname\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dream.dreamname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \"readonly=\"readonly\">\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t内容：\r\n");
      out.write("    \t<div><textarea class=\"demo1-bg\" rows=\"20\" cols=\"60\" name=\"dream1.text\" readonly=\"readonly\">  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dream.text }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </textarea>   \r\n");
      out.write("    \t\t </div> \r\n");
      out.write("    \t\t \r\n");
      out.write("    \t\t \r\n");
      out.write("    \t<div class=\"sumbit\" style=\"margin:auto;width:346px; height:50px;\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t<form action=\"findiddream\"method=\"post\" style=\"float:left;margin-left:10px;\">\r\n");
      out.write("    \t\t<div style=\"margin-left:10px;\"><input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dream.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    \t\t<button class=\"button2\">编辑</button></div>\r\n");
      out.write("    \t</form>\r\n");
      out.write("    \t<div style=\"float:left;margin-left:10px;\">\r\n");
      out.write("    \t<form action=\"/JAVAEE_dreams/main.jsp\">\r\n");
      out.write("    \t\t<button class=\"button1\">返回</button>\r\n");
      out.write("    \t</form>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
